### ISSUE TITLE
v.2.0 errors 

### ISSUE THREAD

**Issue by Varming73** [iPromKnight/zilean#27]
After upgrading my docker container Zilean throws a lot of errors and then stops:

```
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P07: relation "ImdbFiles" already exists
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Zilean.ApiService.Features.Bootstrapping.BootstrapIndexesService.StartingAsync(CancellationToken cancellationToken) in /build/src/Zilean.ApiService/Features/Bootstrapping/BootstrapIndexesService.cs:line 21
   at Zilean.ApiService.Features.Bootstrapping.BootstrapIndexesService.StartingAsync(CancellationToken cancellationToken) in /build/src/Zilean.ApiService/Features/Bootstrapping/BootstrapIndexesService.cs:line 22
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /build/src/Zilean.ApiService/Program.cs:line 31
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "ImdbFiles" already exists
    File: heap.c
    Line: 1149
    Routine: heap_create_with_catalog
     System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateM
     achineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.      
     GetResult(short token)                                                     
  at async Task<bool> Npgsql.NpgsqlDataReader.NextResult(bool async, bool       
     isConsuming, CancellationToken cancellationToken)                          
  at async Task<bool> Npgsql.NpgsqlDataReader.NextResult(bool async, bool       
     isConsuming, CancellationToken cancellationToken)                          
  at async ValueTask<NpgsqlDataReader> Npgsql.NpgsqlCommand.ExecuteReader(bool  
     async, CommandBehavior behavior, CancellationToken cancellationToken)      
  at async ValueTask<NpgsqlDataReader> Npgsql.NpgsqlCommand.ExecuteReader(bool  
     async, CommandBehavior behavior, CancellationToken cancellationToken)      
  at async Task<int> Npgsql.NpgsqlCommand.ExecuteNonQuery(bool async,           
     CancellationToken cancellationToken)                                       
  at async Task<int> Microsoft.EntityFrameworkCore.Storage.RelationalCommand.   
     ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject,     
     CancellationToken cancellationToken)                                       
  at async Task<int> Microsoft.EntityFrameworkCore.Storage.RelationalCommand.   
     ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject,     
     CancellationToken cancellationToken)                                       
  at async Task<int> Microsoft.EntityFrameworkCore.Storage.RelationalCommand.   
     ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject,     
     CancellationToken cancellationToken)                                       
  at async Task                                                                 
     Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.
     ExecuteNonQueryAsync(IEnumerable<MigrationCommand> migrationCommands,      
     IRelationalConnection connection, CancellationToken cancellationToken)     
  at async Task                                                                 
     Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.
     ExecuteNonQueryAsync(IEnumerable<MigrationCommand> migrationCommands,      
     IRelationalConnection connection, CancellationToken cancellationToken)     
  at async Task                                                                 
     Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.
     ExecuteNonQueryAsync(IEnumerable<MigrationCommand> migrationCommands,      
     IRelationalConnection connection, CancellationToken cancellationToken)     
  at async Task                                                                 
     Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.
     ExecuteNonQueryAsync(IEnumerable<MigrationCommand> migrationCommands,      
     IRelationalConnection connection, CancellationToken cancellationToken)     
  at async Task Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.     
     MigrateAsync(string targetMigration, CancellationToken cancellationToken)  
  at async Task                                                                 
     Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.  
     MigrateAsync(string targetMigration, CancellationToken cancellationToken)  
  at async Task                                                                 
     Zilean.ApiService.Features.Bootstrapping.BootstrapIndexesService.          
     StartingAsync(CancellationToken cancellationToken) in                      
     /build/src/Zilean.ApiService/Features/Bootstrapping/                       
     BootstrapIndexesService.cs:21                                              
  at async Task                                                                 
     Zilean.ApiService.Features.Bootstrapping.BootstrapIndexesService.          
     StartingAsync(CancellationToken cancellationToken) in                      
     /build/src/Zilean.ApiService/Features/Bootstrapping/                       
     BootstrapIndexesService.cs:22                                              
  at async Task Microsoft.Extensions.Hosting.Internal.Host.ForeachService<T>(   
     IEnumerable<T> services, CancellationToken token, bool concurrent, bool    
     abortOnFirstException, List<Exception> exceptions, Func<T,                 
     CancellationToken, Task> operation)                                        
[15:30:03] | INFO | "Coravel.Scheduling.HostedService.SchedulerHost" | Coravel's Scheduling service is now stopped.

** Press ANY KEY to close this window ** 
```

**Comment by iPromKnight** [comment]
V2 requires a full reset so removal of both your existing zilean database and your settings file

**Comment by iPromKnight** [comment]
Hey

sorry was posted on discord :)

I’ve updated the release notes on 2.0.0 to include it and will make sure I include going forward. This should be the last reset though
